# Generated by Django 3.2.3 on 2021-06-30 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
