# Generated by Django 3.2.3 on 2021-06-30 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_nwumber', models.CharField(max_length=20)),
                ('name_to', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('address_to', models.CharField(max_length=200)),
                ('telephone_to', models.CharField(max_length=200)),
                ('email_to', models.EmailField(max_length=254)),
                ('box_number_to', models.CharField(max_length=200)),
                ('terms', models.CharField(max_length=200)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vat', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
                ('bank_branch', models.CharField(max_length=200)),
                ('swift_code', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('professional_amount', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_heading', models.CharField(max_length=255)),
                ('prof_sub1', models.CharField(max_length=200)),
                ('prof_sub2', models.CharField(max_length=200)),
                ('prof_sub3', models.CharField(max_length=200)),
                ('prof_sub4', models.CharField(max_length=200)),
                ('prof_sub5', models.CharField(max_length=200)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice')),
            ],
            options={
                'db_table': 'InvoiceLineItem',
            },
        ),
        migrations.CreateModel(
            name='Disbursements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_amount', models.CharField(max_length=200)),
                ('disb_heading', models.CharField(max_length=200)),
                ('disb_sub1', models.CharField(max_length=200)),
                ('disb_sub2', models.CharField(max_length=200)),
                ('disb_sub3', models.CharField(max_length=200)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice')),
            ],
            options={
                'db_table': 'Disbursements',
            },
        ),
    ]
