# Generated by Django 3.2.3 on 2021-07-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210702_1149'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
        migrations.AlterModelTable(
            name='invoicelineitem',
            table='lineItem',
        ),
    ]
