# Generated by Django 3.2.3 on 2021-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210726_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursements',
            name='disb_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disbursements',
            name='disbursement_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
